/* eslint-disable */
require('./close')
require('./delete')
require('./down')
require('./hamburg')
require('./home')
require('./homedeal')
require('./hometoday')
require('./homeweek')
require('./homeyesterday')
require('./inquirymanager')
require('./logo')
require('./materielmanager')
require('./tatisticsmanager')
require('./up')
require('./usermanager')
require('./vue')
